INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Oasis Club Teatro','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Oasis Club Teatro','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Oasis Club Teatro','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('The Royal Club','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('The Royal Club','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El Plata','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El Plata','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Fox Tabern','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Fox Tabern','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Fox Tabern','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Point Salamero','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Point Salamero','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Snatch Club','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Snatch Club','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El Cielo','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El Cielo','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El Cielo','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Kenbo','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Kenbo','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Kenbo','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Kenbo','Años 60-80');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Posturas','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Epoca Dorada','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Epoca Dorada','Años 60-80');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Epoca Dorada','Indie');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Barrio Club','Rap');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Super8','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Super8','Latina');