INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Martinica','/imgBares/martinica1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Martinica','/imgBares/martinica2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Buscón','/imgBares/buscon1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Buscón','/imgBares/buscon2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Encantadora','/imgBares/encantadora1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','/imgBares/manolo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','/imgBares/manolo2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El licenciado Vidriera','/imgBares/licenciado1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','/imgBares/daluxe1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','/imgBares/daluxe2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','/imgBares/daluxe3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El jardin del Temple','/imgBares/jardin1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El jardin del Temple','/imgBares/jardin2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Mina','/imgBares/mina1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Cucaracha','/imgBares/cucaracha1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Casa del Loco','/imgBares/casaloco1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Vivalavida','/imgBares/vivalavida1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El licenciado Vidriera','/imgBares/tres');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','/imgBares/tres');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Mina','/imgBares/tres');