INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/elplataEv1','El Plata');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/epocadoradaEv1','Epoca Dorada');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/foxEv1','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/foxEv2','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/foxEv3','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/kenboEv1','Kenbo');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/kenboEv2','Kenbo');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/oasisEv1','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/oasisEv2','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/oasisEv3','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv1','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv2','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv3','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv4','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv5','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/snatchEv1','Snatch Club');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/super8Ev1','Super8');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/super8Ev2','Super8');