INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Oasis Club Teatro','/imgBares/oasis1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Oasis Club Teatro','/imgBares/oasis2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Barrio Club','/imgBares/barrioclub1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Barrio Club','/imgBares/barrioclub2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Cielo','/imgBares/elcielo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Plata','/imgBares/elplata1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Plata','/imgBares/elplata2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Epoca Dorada','/imgBares/epocadorada1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Epoca Dorada','/imgBares/epocadorada2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','/imgBares/fox1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','/imgBares/fox2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','/imgBares/fox3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Point Salamero','/imgBares/point1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Point Salamero','/imgBares/point2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Posturas','/imgBares/posturas1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Posturas','/imgBares/posturas2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','/imgBares/royal1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','/imgBares/royal2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','/imgBares/royal3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Snatch Club','/imgBares/snatch1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Snatch Club','/imgBares/snatch2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','/imgBares/kenbo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','/imgBares/kenbo2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','/imgBares/kenbo3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','/imgBares/super81');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','/imgBares/super82');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','/imgBares/super83');
