INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Casa del Loco','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Casa del Loco','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El jardin del Temple','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El jardin del Temple','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El jardin del Temple','Electronica');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Vivalavida','Indie');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Vivalavida','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Vivalavida','Electronica');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Mina','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Mina','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Cafe da Luxe','Electronica');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Cafe da Luxe','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Cucaracha','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Cucaracha','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El licenciado Vidriera','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El licenciado Vidriera','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Manolo La Nuit','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Manolo La Nuit','Rock/Heavy');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('Manolo La Nuit','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Encantadora','Electronica');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El Buscón','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El Buscón','Pop/musica comercial');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('El Buscón','Electronica');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Martinica','Electronica');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Martinica','Latina');
INSERT INTO `hay` (`nombre`,`musica`) VALUES ('La Martinica','Pop/musica comercial');