INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('La Martinica','Hablar del Casco es hacerlo de uno de los bares con más solera. Fiestas Erasmus, organizadas o temáticas. El caso es que cada fin de semana es uno de los puntos de encuentro de referencia de la ciudad.','C/ Manifestación, 15',18,'00:00','4:00',699971180,'','https://www.facebook.com/lamartinica.zaragoza');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('El Buscón','Dos pisos de buen ambiente, intimidad y fiesta. Cada fin de semana el que se retrasa no sale en la foto, ya que es uno de los establecimientos que más se suele llenar. Lo último en música y un amplio espacio para bailarla.','C/ Temple, 8',18,'23:45','3:30',976299006,'','https://www.facebook.com/El-buscon-1508615362743015/');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('La Encantadora','Uno de los locales con más capacidad del Casco Viejo. En la calle del Temple, este local mezcla la tradición (con una peculiar decoración) con la modernidad (a la hora de pinchar música). Un amplio espacio con cabida para un amplio abanico de edades.','C/ Temple, 17',18,'00:00','4:00',665217125,'','https://www.facebook.com/la.cascoviejo');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('Manolo La Nuit','Hablar del Casco es hacerlo de uno de los bares con más solera. Fiestas Erasmus, organizadas o temáticas. El caso es que cada fin de semana es uno de los puntos de encuentro de referencia de la ciudad.','C/ Temple, 20',18,'23:30','4:30',660570465,'info@territoriocucaracha.es','https://www.facebook.com/manololanuitzgz/');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('El licenciado Vidriera','Uno de los grandes clásicos del Casco Viejo. Su ron, sus mojitos y sus músicas de ayer y de hoy le convierten en un gran foro festivo con cabida para todo tipo de generaciones. Un espacio que no deja indiferente a nadie y que llama la atención de todos.','C/ Temple, 29',18,'22:00','3:30',678655246,'info@territoriocucaracha.es','https://www.facebook.com/licenciadovidrierazgz/');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('La Cucaracha','Sinónimo de "machacaos", este local es otro de los grandes clásicos en las noches de ayer y de hoy. Especialistas en chupitos, este bar es un lugar de encuentro para todos los que quieren realizar la mezcla especial con sprite y su ingrediente secreto','C/ Temple, 27',18,'22:30','4:30',699971180,'info@territoriocucaracha.es','https://www.facebook.com/lacucarachazgz/');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('Cafe da Luxe','En plena plaza del Pilar, lleva ofreciendo marcha hasta el amanecer desde el año 2006. Terraza, coctelería "de luxe" y dos plantas con ambientes diferentes para disfrutar la noche de Zaragoza con los mejores djs y la mejor gente hasta el amanecer. También apuestan por el humor.','Plaza del Pilar, 12',18,'20:00','6:30',976295877,'eljardindeltemple@gmail.com','https://www.facebook.com/DaLuxeZgz/');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('El jardin del Temple','Uno de los bares más amplios de la calle del Temple. También es uno de los grandes clásicos. Con el paso de los años no ha perdido adeptos y sigue siendo un bar de cabecera para muchos jóvenes y para otros que ya no lo son tanto. Su música varia de un extremo a otro','C/ Temple, 18',18,'23:00','4:00',976200763,'','https://www.facebook.com/jardindeltemple/');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('La Mina','Cada año suele organizar fiestas Erasmus con el objetivo de crear un ambiente joven y universitario dentro de su local. Del mismo modo, también tiene una amplia carta de chupitos que ofrecer a sus clientes.','C/ Contamina, 13',18,'23:00','4:00',635803809,'superbarmina@gmail.com','https://www.facebook.com/lamina.cascoviejo');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('La Casa del Loco','Un local mítico. Desde febrero de 1988 la calle Mayor tiene una de las grandes referencias en la fiesta zaragozana.','C/ Mayor, 10',18,'00:00','6:30',976396771,'lolamoreno13@gmail.com','https://www.facebook.com/La-Casa-del-Loco-36750004633/');
INSERT INTO `bar` (`nombre`,`descripcion`,`direccion`,`edad`,`horarioApertura`,`horarioCierre`,`telefono`,`email`,`facebook`) VALUES ('Vivalavida','Se trata de un lugar distinto dedicado, según aseguran en sus redes, al amor. Entre sus cuatro paredes es habitual ver caras conocidas de la música y la cultura como Violadores del Verso o Antílope León (uno de sus dueños).','C/ Santa Cruz, 7',18,'23:30','4:00',NULL,'','https://www.facebook.com/Vivalavida-353970834771269/');

http://www.redaragon.com/ocio/copas/noticia.asp?pkid=3494
https://twitter.com/lamartinicazgz
http://www.aplace2go.com/ficha/fiesta-bar-de-copas-bar-zaragoza-casco-antiguo-la-martinica/22