INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/martinicaEv1','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/martinicaEv2','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/martinicaEv3','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/busconEv1','El Buscón');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/encantadoraEv1','La Encantadora');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/encantadoraEv2','La Encantadora');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/manoloEv1','Manolo La Nuit');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/manoloEv2','Manolo La Nuit');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/licenciadoEv1','El licenciado Vidriera');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/daluxeEv1','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/daluxeEv2','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/daluxeEv3','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/jardinEv1','El jardin del Temple');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/jardinEv2','El jardin del Temple');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/minaEv1','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/minaEv2','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/minaEv3','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/casalocoEv1','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/casalocoEv2','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/casalocoEv3','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/vivalavidaEv1','Vivalavida');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/vivalavidaEv2','Vivalavida');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/vivalavidaEv3','Vivalavida');