-- MySQL Script generated by MySQL Workbench
-- 03/21/16 13:50:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fyb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fyb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fyb` DEFAULT CHARACTER SET utf8 ;
USE `fyb` ;

-- -----------------------------------------------------
-- Table `fyb`.`bar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fyb`.`bar` (
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `direccion` VARCHAR(200) NULL,
  `edad` INT NULL,
  `horarioApertura` VARCHAR(5) NULL,
  `horarioCierre` VARCHAR(5) NULL,
  `telefono` INT NULL,
  `email` VARCHAR(50) NULL,
  `facebook` VARCHAR(200) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fyb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fyb`.`evento` (
  `evento` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fyb`.`tipomusica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fyb`.`tipomusica` (
  `musica` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`musica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fyb`.`hace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fyb`.`hace` (
  `evento` VARCHAR(200) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`evento`, `nombre`),
  INDEX `nombre_idx` (`nombre` ASC),
  CONSTRAINT `evento`
    FOREIGN KEY (`evento`)
    REFERENCES `fyb`.`evento` (`evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bar`
    FOREIGN KEY (`nombre`)
    REFERENCES `fyb`.`bar` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fyb`.`hay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fyb`.`hay` (
  `nombre` VARCHAR(50) NOT NULL,
  `musica` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`nombre`, `musica`),
  INDEX `nombre_idx` (`musica` ASC),
  CONSTRAINT `nombre`
    FOREIGN KEY (`nombre`)
    REFERENCES `fyb`.`bar` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `musica`
    FOREIGN KEY (`musica`)
    REFERENCES `fyb`.`tipomusica` (`musica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fyb`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fyb`.`imagen` (
  `imagenId` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(50) NULL,
  PRIMARY KEY (`imagenId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fyb`.`tiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fyb`.`tiene` (
  `nombreId` VARCHAR(50) NOT NULL,
  `imagenId` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nombreId`, `imagenId`),
  INDEX `imagen_idx` (`imagenId` ASC),
  CONSTRAINT `nombreId`
    FOREIGN KEY (`nombreId`)
    REFERENCES `fyb`.`bar` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `imagenId`
    FOREIGN KEY (`imagenId`)
    REFERENCES `fyb`.`imagen` (`imagenId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
