INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Martinica','/imgBares/martinica1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Martinica','/imgBares/martinica2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Buscón','/imgBares/buscon1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Buscón','/imgBares/buscon2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Encantadora','/imgBares/encantadora1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','/imgBares/manolo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','/imgBares/manolo2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El licenciado Vidriera','/imgBares/licenciado1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','/imgBares/daluxe1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','/imgBares/daluxe2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','/imgBares/daluxe3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El jardin del Temple','/imgBares/jardin1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El jardin del Temple','/imgBares/jardin2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Mina','/imgBares/mina1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Cucaracha','/imgBares/cucaracha1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Casa del Loco','/imgBares/casaloco1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Vivalavida','/imgBares/vivalavida1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El licenciado Vidriera','/imgBares/tres');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','/imgBares/tres');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Mina','/imgBares/tres');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Oasis Club Teatro','/imgBares/oasis1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Oasis Club Teatro','/imgBares/oasis2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Barrio Club','/imgBares/barrioclub1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Barrio Club','/imgBares/barrioclub2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Cielo','/imgBares/elcielo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Plata','/imgBares/elplata1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Plata','/imgBares/elplata2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Epoca Dorada','/imgBares/epocadorada1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Epoca Dorada','/imgBares/epocadorada2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','/imgBares/fox1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','/imgBares/fox2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','/imgBares/fox3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Point Salamero','/imgBares/point1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Point Salamero','/imgBares/point2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Posturas','/imgBares/posturas1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Posturas','/imgBares/posturas2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','/imgBares/royal1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','/imgBares/royal2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','/imgBares/royal3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Snatch Club','/imgBares/snatch1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Snatch Club','/imgBares/snatch2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','/imgBares/kenbo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','/imgBares/kenbo2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','/imgBares/kenbo3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','/imgBares/super81');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','/imgBares/super82');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','/imgBares/super83');