INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/martinicaEv1','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/martinicaEv2','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/martinicaEv3','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/busconEv1','El Buscón');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/encantadoraEv1','La Encantadora');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/encantadoraEv2','La Encantadora');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/manoloEv1','Manolo La Nuit');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/manoloEv2','Manolo La Nuit');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/licenciadoEv1','El licenciado Vidriera');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/daluxeEv1','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/daluxeEv2','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/daluxeEv3','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/jardinEv1','El jardin del Temple');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/jardinEv2','El jardin del Temple');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/minaEv1','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/minaEv2','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/minaEv3','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/casalocoEv1','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/casalocoEv2','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/casalocoEv3','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/vivalavidaEv1','Vivalavida');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/vivalavidaEv2','Vivalavida');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/vivalavidaEv3','Vivalavida');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/elplataEv1','El Plata');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/epocadoradaEv1','Epoca Dorada');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/foxEv1','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/foxEv2','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/foxEv3','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/kenboEv1','Kenbo');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/kenboEv2','Kenbo');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/oasisEv1','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/oasisEv2','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/oasisEv3','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv1','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv2','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv3','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv4','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/pointEv5','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/snatchEv1','Snatch Club');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/super8Ev1','Super8');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('/imgEventos/super8Ev2','Super8');