INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/martinicaEv1','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/martinicaEv2','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/martinicaEv3','La Martinica');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/busconEv1','El Buscón');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/encantadoraEv1','La Encantadora');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/encantadoraEv2','La Encantadora');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/manoloEv1','Manolo La Nuit');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/manoloEv2','Manolo La Nuit');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/licenciadoEv1','El licenciado Vidriera');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/daluxeEv1','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/daluxeEv2','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/daluxeEv3','Cafe da Luxe');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/jardinEv1','El jardin del Temple');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/jardinEv2','El jardin del Temple');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/minaEv1','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/minaEv2','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/minaEv3','La Mina');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/casalocoEv1','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/casalocoEv2','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/casalocoEv3','La Casa del Loco');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/vivalavidaEv1','Vivalavida');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/vivalavidaEv2','Vivalavida');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/vivalavidaEv3','Vivalavida');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/elplataEv1','El Plata');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/epocadoradaEv1','Epoca Dorada');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/foxEv1','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/foxEv2','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/foxEv3','Fox Tabern');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/kenboEv1','Kenbo');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/kenboEv2','Kenbo');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/oasisEv1','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/oasisEv2','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/oasisEv3','Oasis Club Teatro');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/pointEv1','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/pointEv2','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/pointEv3','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/pointEv4','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/pointEv5','Point Salamero');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/snatchEv1','Snatch Club');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/super8Ev1','Super8');
INSERT INTO `hace` (`evento`,`nombre`) VALUES ('ps1516.ddns.net/images/imgEventos/super8Ev2','Super8');