INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Martinica','ps1516.ddns.net/images/imgBares/martinica1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Martinica','ps1516.ddns.net/images/imgBares/martinica2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Buscón','ps1516.ddns.net/images/imgBares/buscon1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Buscón','ps1516.ddns.net/images/imgBares/buscon2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Encantadora','ps1516.ddns.net/images/imgBares/encantadora1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','ps1516.ddns.net/images/imgBares/manolo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','ps1516.ddns.net/images/imgBares/manolo2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El licenciado Vidriera','ps1516.ddns.net/images/imgBares/licenciado1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','ps1516.ddns.net/images/imgBares/daluxe1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','ps1516.ddns.net/images/imgBares/daluxe2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Cafe da Luxe','ps1516.ddns.net/images/imgBares/daluxe3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El jardin del Temple','ps1516.ddns.net/images/imgBares/jardin1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El jardin del Temple','ps1516.ddns.net/images/imgBares/jardin2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Mina','ps1516.ddns.net/images/imgBares/mina1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Cucaracha','ps1516.ddns.net/images/imgBares/cucaracha1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Casa del Loco','ps1516.ddns.net/images/imgBares/casaloco1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Vivalavida','ps1516.ddns.net/images/imgBares/vivalavida1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El licenciado Vidriera','ps1516.ddns.net/images/imgBares/tres');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Manolo La Nuit','ps1516.ddns.net/images/imgBares/tres');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('La Mina','ps1516.ddns.net/images/imgBares/tres');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Oasis Club Teatro','ps1516.ddns.net/images/imgBares/oasis1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Oasis Club Teatro','ps1516.ddns.net/images/imgBares/oasis2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Barrio Club','ps1516.ddns.net/images/imgBares/barrioclub1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Barrio Club','ps1516.ddns.net/images/imgBares/barrioclub2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Cielo','ps1516.ddns.net/images/imgBares/elcielo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Plata','ps1516.ddns.net/images/imgBares/elplata1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('El Plata','ps1516.ddns.net/images/imgBares/elplata2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Epoca Dorada','ps1516.ddns.net/images/imgBares/epocadorada1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Epoca Dorada','ps1516.ddns.net/images/imgBares/epocadorada2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','ps1516.ddns.net/images/imgBares/fox1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','ps1516.ddns.net/images/imgBares/fox2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Fox Tabern','ps1516.ddns.net/images/imgBares/fox3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Point Salamero','ps1516.ddns.net/images/imgBares/point1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Point Salamero','ps1516.ddns.net/images/imgBares/point2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Posturas','ps1516.ddns.net/images/imgBares/posturas1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Posturas','ps1516.ddns.net/images/imgBares/posturas2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','ps1516.ddns.net/images/imgBares/royal1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','ps1516.ddns.net/images/imgBares/royal2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('The Royal Club','ps1516.ddns.net/images/imgBares/royal3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Snatch Club','ps1516.ddns.net/images/imgBares/snatch1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Snatch Club','ps1516.ddns.net/images/imgBares/snatch2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','ps1516.ddns.net/images/imgBares/kenbo1');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','ps1516.ddns.net/images/imgBares/kenbo2');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Kenbo','ps1516.ddns.net/images/imgBares/kenbo3');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','ps1516.ddns.net/images/imgBares/super81');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','ps1516.ddns.net/images/imgBares/super82');
INSERT INTO `tiene` (`nombreId`,`imagenId`) VALUES ('Super8','ps1516.ddns.net/images/imgBares/super83');