INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('La Martinica','http://ps1516.ddns.net/images/imgBares/martinica1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('La Martinica','http://ps1516.ddns.net/images/imgBares/martinica2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El Buscón','http://ps1516.ddns.net/images/imgBares/buscon1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El Buscón','http://ps1516.ddns.net/images/imgBares/buscon2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('La Encantadora','http://ps1516.ddns.net/images/imgBares/encantadora1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Manolo La Nuit','http://ps1516.ddns.net/images/imgBares/manolo1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Manolo La Nuit','http://ps1516.ddns.net/images/imgBares/manolo2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El licenciado Vidriera','http://ps1516.ddns.net/images/imgBares/licenciado1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Cafe da Luxe','http://ps1516.ddns.net/images/imgBares/daluxe1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Cafe da Luxe','http://ps1516.ddns.net/images/imgBares/daluxe2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Cafe da Luxe','http://ps1516.ddns.net/images/imgBares/daluxe3','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El jardin del Temple','http://ps1516.ddns.net/images/imgBares/jardin1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El jardin del Temple','http://ps1516.ddns.net/images/imgBares/jardin2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('La Mina','http://ps1516.ddns.net/images/imgBares/mina1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('La Cucaracha','http://ps1516.ddns.net/images/imgBares/cucaracha1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('La Casa del Loco','http://ps1516.ddns.net/images/imgBares/casaloco1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Vivalavida','http://ps1516.ddns.net/images/imgBares/vivalavida1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El licenciado Vidriera','http://ps1516.ddns.net/images/imgBares/tres','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Manolo La Nuit','http://ps1516.ddns.net/images/imgBares/tres','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('La Mina','http://ps1516.ddns.net/images/imgBares/tres','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Oasis Club Teatro','http://ps1516.ddns.net/images/imgBares/oasis1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Oasis Club Teatro','http://ps1516.ddns.net/images/imgBares/oasis2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Barrio Club','http://ps1516.ddns.net/images/imgBares/barrioclub1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Barrio Club','http://ps1516.ddns.net/images/imgBares/barrioclub2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El Cielo','http://ps1516.ddns.net/images/imgBares/elcielo1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El Plata','http://ps1516.ddns.net/images/imgBares/elplata1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('El Plata','http://ps1516.ddns.net/images/imgBares/elplata2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Epoca Dorada','http://ps1516.ddns.net/images/imgBares/epocadorada1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Epoca Dorada','http://ps1516.ddns.net/images/imgBares/epocadorada2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Fox Tabern','http://ps1516.ddns.net/images/imgBares/fox1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Fox Tabern','http://ps1516.ddns.net/images/imgBares/fox2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Fox Tabern','http://ps1516.ddns.net/images/imgBares/fox3','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Point Salamero','http://ps1516.ddns.net/images/imgBares/point1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Point Salamero','http://ps1516.ddns.net/images/imgBares/point2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Posturas','http://ps1516.ddns.net/images/imgBares/posturas1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Posturas','http://ps1516.ddns.net/images/imgBares/posturas2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('The Royal Club','http://ps1516.ddns.net/images/imgBares/royal1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('The Royal Club','http://ps1516.ddns.net/images/imgBares/royal2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('The Royal Club','http://ps1516.ddns.net/images/imgBares/royal3','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Snatch Club','http://ps1516.ddns.net/images/imgBares/snatch1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Snatch Club','http://ps1516.ddns.net/images/imgBares/snatch2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Kenbo','http://ps1516.ddns.net/images/imgBares/kenbo1','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Kenbo','http://ps1516.ddns.net/images/imgBares/kenbo2','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Kenbo','http://ps1516.ddns.net/images/imgBares/kenbo3','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Super8','http://ps1516.ddns.net/images/imgBares/super81','principal');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Super8','http://ps1516.ddns.net/images/imgBares/super82','secundaria');
INSERT INTO `imagen` (`nombreId`,`imagenId`,`tipo`) VALUES ('Super8','http://ps1516.ddns.net/images/imgBares/super83','secundaria');